### ISSUE TITLE
Bad preview in the "Welcome" slides

### ISSUE THREAD

**Issue by BenjaFriend** [RITGameDev/game-dev-club-site#15]
![image](https://user-images.githubusercontent.com/14983811/64868875-2c24b480-d60e-11e9-8ffb-388743bd6f90.png)

That `Presentation` looks like it should be a link but its not. This can be fixe dby adding some text in the actual Welcome post before the title, or setting the preview meta data manually for the post.

**Comment by Dayn9** [comment]
I think this has something to do with {{post.excerpt}}

**Comment by Dayn9** [comment]
fixed
