### ISSUE TITLE
Many beginners are likely unfamiliar with Jekyll; needs more details

### ISSUE THREAD

**Issue by Argzero** [RITGameDev/game-dev-club-site#9]
Many beginners are likely unfamiliar with Jekyll, how it works, and what it does (in some detail). As such, the readme should include a rudimentary explanation of what Jekyll is, motivations for using it here, and how people might use it elsewhere. 

As an added note, template readme content ought to be removed.

**Comment by BenjaFriend** [comment]
That's what the link to the Jekyll tut is for in the readme ¯\_(ツ)_/¯

**Comment by Argzero** [comment]
Still unclear what its purpose is to the layperson.
